"""choices table

Revision ID: 6bb8a7489ee1
Revises: 0942ca5fc7af
Create Date: 2023-03-17 23:14:49.303563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bb8a7489ee1'
down_revision = '0942ca5fc7af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('choice', schema=None) as batch_op:
        batch_op.drop_index('ix_choice_test')
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('choice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.VARCHAR(length=128), nullable=True))
        batch_op.create_index('ix_choice_test', ['test'], unique=False)

    # ### end Alembic commands ###
