"""templates table

Revision ID: 6fb10dcd9990
Revises: a1ca3bd0d7b0
Create Date: 2023-03-17 22:53:17.763061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb10dcd9990'
down_revision = 'a1ca3bd0d7b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_template_name'), ['name'], unique=False)

    op.create_table('choice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('choice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_choice_value'), ['value'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('choice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_choice_value'))

    op.drop_table('choice')
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_template_name'))

    op.drop_table('template')
    # ### end Alembic commands ###
