"""templates table

Revision ID: 776b241dc03d
Revises: 6bb8a7489ee1
Create Date: 2023-03-17 23:16:30.942597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776b241dc03d'
down_revision = '6bb8a7489ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('choice', schema=None) as batch_op:
        batch_op.drop_index('ix_choice_value')

    op.drop_table('choice')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('choice',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('value', sa.VARCHAR(length=128), nullable=True),
    sa.Column('template_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('choice', schema=None) as batch_op:
        batch_op.create_index('ix_choice_value', ['value'], unique=False)

    # ### end Alembic commands ###
